### ISSUE TITLE
Timeout errors on ~10MB blobs

### ISSUE THREAD

**Issue by jakobht** [PotionalDev/azurex#1]
First of all thanks a lot for this library!

I'm trying to `put` a blob which is around 10mb big. I configured at then I run the code:

```elixir
# Make a blob of 16mb
blob = for x <- 1..(1024*1024), into: <<>> do <<Enum.random(0..255)>> end
blob = Enum.reduce(1..14, blob, fn (_, x) -> x <> x end)

# Create it 
Azurex.Blob.put_blob("blob", blob, "application/octet-stream")
```
This returns:
```elixir
{:error, %HTTPoison.Error{id: nil, reason: :timeout}}
```
Interestingly:
1. The blob is created, and when I download it, it _is_ the blob I uploaded. 
2. This only happens for "bigger" binaries if the binary is e.g. 1kb the return is as expected.

I understand that the error is just propagated from HTTPoison, but I thought you might have some insights?

**Comment by kaaboaye** [comment]
Since I'm not mantianing this library anymore I would recommend forking it.

## How to fix this issue?

Maybe try increasing timeout here https://github.com/PotionalDev/azurex/blob/master/lib/azurex/blob.ex#L25

**Comment by jakobht** [comment]
Thanks for the reply and the suggestion. And thanks again for making the library it in the first place!

**Comment by jakobht** [comment]
Hi again
Sorry to bug you again. I just want to make sure it's ok if the code is published under an MIT license. You have not specified any license so I just wanted to make sure :) .

**Comment by kaaboaye** [comment]
Sure, no problem
